export const permissionCatalog = [
  ["affiliates:read", "Affiliates", "affiliates", "read", "View referral network and commission reports", "medium"],
  ["affiliates:update", "Affiliates", "affiliates", "update", "Configure affiliate rates and availability", "high"],
  ["affiliates:payout", "Affiliates", "affiliates", "payout", "Record affiliate payouts and reverse commissions", "critical"],
  ["access:read", "Access", "access", "read", "View access management", "medium"],
  ["access:manage", "Access", "access", "manage", "Manage the complete authorization system", "critical"],
  ["staff:read", "Staff", "staff", "read", "View staff members", "medium"],
  ["staff:create", "Staff", "staff", "create", "Invite and create staff", "high"],
  ["staff:update", "Staff", "staff", "update", "Update or suspend staff", "high"],
  ["staff:delete", "Staff", "staff", "delete", "Deactivate staff", "critical"],
  ["roles:read", "Roles", "roles", "read", "View roles and effective permissions", "medium"],
  ["roles:create", "Roles", "roles", "create", "Create or clone custom roles", "high"],
  ["roles:update", "Roles", "roles", "update", "Edit custom roles and permissions", "critical"],
  ["roles:delete", "Roles", "roles", "delete", "Delete custom roles", "critical"],
  ["roles:assign", "Roles", "roles", "assign", "Assign roles to staff", "critical"],
  ["permissions:read", "Permissions", "permissions", "read", "View permission definitions", "medium"],
  ["permissions:manage", "Permissions", "permissions", "manage", "Grant direct permission overrides", "critical"],
  ["audit:read", "Audit", "audit", "read", "View immutable security audit events", "high"],
  ["audit:export", "Audit", "audit", "export", "Export security audit events", "high"],
  ["users:read", "Users", "users", "read", "View customer accounts", "medium"],
  ["users:create", "Users", "users", "create", "Create customer accounts", "high"],
  ["users:update", "Users", "users", "update", "Update customer access", "high"],
  ["users:impersonate", "Users", "users", "impersonate", "Open an audited read-only customer preview", "critical"],
  ["users:delete", "Users", "users", "delete", "Close customer accounts", "critical"],
  ["billing:read", "Billing", "billing", "read", "View billing and balances", "medium"],
  ["billing:update", "Billing", "billing", "update", "Adjust billing and credits", "critical"],
  ["reports:read", "Reports", "reports", "read", "View platform analytics", "low"],
  ["reports:export", "Reports", "reports", "export", "Export platform analytics", "medium"],
  ["settings:read", "Settings", "settings", "read", "View platform settings", "medium"],
  ["settings:update", "Settings", "settings", "update", "Update platform settings and secrets", "critical"],
  ["products:read", "Products", "products", "read", "View product catalog", "low"],
  ["products:update", "Products", "products", "update", "Manage products and credit costs", "high"],
  ["strategies:read", "Strategies", "strategies", "read", "View strategy catalog", "low"],
  ["strategies:update", "Strategies", "strategies", "update", "Publish and configure strategies", "high"],
  ["signals:read", "Signals", "signals", "read", "Review published research", "low"],
  ["signals:update", "Signals", "signals", "update", "Moderate published research", "high"],
  ["orders:read", "Orders", "orders", "read", "View order activity", "high"],
  ["orders:update", "Orders", "orders", "update", "Manage order operations", "critical"],
  ["support:read", "Support", "support", "read", "View tenant support tickets", "medium"],
  ["support:update", "Support", "support", "update", "Respond to and resolve tickets", "medium"],
  ["emails:read", "Email", "emails", "read", "View email delivery configuration", "medium"],
  ["emails:update", "Email", "emails", "update", "Send tests and configure email", "high"],
  ["notifications:create", "Notifications", "notifications", "create", "Send platform notifications", "high"],
  ["data:read", "Data", "data", "read", "View operational data explorer", "high"],
  ["data:export", "Data", "data", "export", "Export operational data", "critical"],
] as const;

export type PermissionKey = (typeof permissionCatalog)[number][0];

const operationalRead = ["reports:read", "products:read", "strategies:read", "signals:read", "orders:read", "support:read"];
export const systemRoleTemplates = [
  { slug: "super-admin", name: "Super Admin", description: "Unrestricted platform owner. Assignment is tightly protected.", superAdmin: true, permissions: ["*:*"] },
  { slug: "admin", name: "Admin", description: "Tenant administration without Super Admin role governance.", superAdmin: false, permissions: [...operationalRead, "users:read", "users:update", "users:impersonate", "billing:read", "billing:update", "settings:read", "products:update", "strategies:update", "signals:update", "orders:update", "support:update", "emails:read", "emails:update", "notifications:create", "staff:read", "roles:read", "permissions:read", "audit:read"] },
  { slug: "manager", name: "Manager", description: "Operational manager with review and workflow permissions.", superAdmin: false, permissions: [...operationalRead, "users:read", "billing:read", "signals:update", "orders:update", "support:update"] },
  { slug: "staff", name: "Staff", description: "Least-privilege operational staff access.", superAdmin: false, permissions: operationalRead },
  { slug: "customer", name: "Customer", description: "Standard customer workspace access.", superAdmin: false, permissions: [] },
] as const;
