import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight, CircleDot, Eye, ShieldCheck } from "lucide-react";

export const metadata: Metadata = { title: "About", description: "Why Enrivea is building a more transparent crypto research and decision workspace." };

export default function AboutPage() {
  return <main><section className="relative overflow-hidden border-b border-line"><div className="pointer-events-none absolute inset-0 hero-mesh opacity-45"/><div className="relative mx-auto grid max-w-[1500px] gap-10 px-5 py-24 sm:px-8 lg:grid-cols-2 lg:gap-16 lg:px-12 lg:py-32"><div><p className="eyebrow">About Enrivea Signal</p><h1 className="display mt-5 text-5xl sm:text-7xl">Clarity is a <span className="text-accent">trading tool.</span></h1></div><div className="self-end text-lg leading-8 text-muted"><p>Crypto markets move quickly. That makes it easy for a signal to sound certain even when the underlying evidence is thin.</p><p className="mt-5">Enrivea Signal is being built by Enrivea to make the research process inspectable: a defined setup, a recorded reason, a visible invalidation, and an outcome counted after publication.</p></div></div></section>
    <section className="mx-auto max-w-[1500px] px-5 py-24 sm:px-8 lg:px-12 lg:py-28"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Our principles</p><h2 className="display mt-5 text-4xl sm:text-5xl">The standard behind <span className="text-accent">the interface.</span></h2></div><p className="max-w-xl self-end text-lg leading-8 text-muted">A premium tool is not just fast or visually polished. It should help people understand the limits of a conclusion before they put capital at risk.</p></div><div className="mt-14 grid gap-4 lg:grid-cols-3"><Value icon={<Eye/>} title="Show the reasoning" text="A published idea should include the market facts, its thesis, its risk condition, and a time limit—not only an action label."/><Value icon={<CircleDot/>} title="Count every outcome" text="An expired or losing idea belongs in the record alongside a winning one. Paper methods and real fills must never be blended."/><Value icon={<ShieldCheck/>} title="Keep people in control" text="The product does not take custody. Connected orders must be previewed and explicitly approved by the account owner."/></div></section>
    <section className="border-y border-line bg-[#111914]"><div className="mx-auto grid max-w-[1500px] gap-8 px-5 py-24 sm:px-8 lg:grid-cols-2 lg:px-12"><div className="rounded-[22px] border border-[#3c503d] bg-[#18221a] p-8"><p className="eyebrow">What the model does</p><h3 className="mt-5 text-2xl font-bold">Explain evidence and uncertainty.</h3><p className="mt-5 text-base leading-8 text-muted">When a deterministic market screen identifies a qualifying setup, AI receives the calculated facts and turns them into a readable thesis and risk note. The aim is to make the reasoning easier to question.</p></div><div className="rounded-[22px] border border-[#3c503d] bg-[#18221a] p-8"><p className="eyebrow">What the model does not do</p><h3 className="mt-5 text-2xl font-bold">Invent prices or promise outcomes.</h3><p className="mt-5 text-base leading-8 text-muted">Entry, invalidation, and target levels are calculated in code. A model narrative is not a probability of success, personalized investment advice, or permission to execute an order.</p></div></div></section>
    <section className="mx-auto grid max-w-[1500px] gap-10 px-5 py-24 sm:px-8 lg:grid-cols-[.9fr_1.1fr] lg:px-12 lg:py-28"><div><p className="eyebrow">An Enrivea product</p><h2 className="display mt-5 text-4xl sm:text-5xl">Research you can <span className="text-accent">question.</span></h2></div><div><p className="text-lg leading-8 text-muted">Enrivea Signal is part of Enrivea&apos;s product family. It is being developed in stages: a transparent research desk first, then guarded exchange connectivity, and only then paid access in approved countries.</p><p className="mt-5 text-base leading-7 text-muted">We will not use a paper chart to claim real trading returns. The product will distinguish its assumptions, data sources, and operational state as it grows.</p><Link href="/register" className="button-primary mt-8 inline-flex items-center gap-2 rounded-xl px-6 py-3 text-sm">Explore the workspace <ArrowUpRight className="size-4"/></Link></div></section></main>;
}

function Value({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="surface rounded-[22px] p-7"><span className="flex size-11 items-center justify-center rounded-xl bg-[#c5ff4119] text-accent [&>svg]:size-5">{icon}</span><h3 className="mt-9 text-xl font-bold">{title}</h3><p className="mt-3 text-base leading-7 text-muted">{text}</p></div>; }
