import type { Metadata } from "next";
import { ArrowUpRight, Headset, Mail, ShieldCheck } from "lucide-react";
import { ContactForm } from "@/components/contact-form";

export const metadata: Metadata = { title: "Contact", description: "Contact the Enrivea Signal team about the product, your account, or partnerships." };

export default function ContactPage() {
  return <main className="mx-auto max-w-[1500px] px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="mb-14 grid gap-8 lg:grid-cols-[.85fr_1.15fr]"><div><p className="eyebrow">Contact Enrivea Signal</p><h1 className="display mt-5 text-5xl sm:text-6xl">A direct line to <span className="text-accent">our team.</span></h1></div><p className="max-w-xl self-end text-lg leading-8 text-muted">Questions about the research desk, your account, accessibility, or partnerships? Tell us enough to help, but never include passwords or exchange API credentials.</p></div><div className="grid gap-8 lg:grid-cols-[.7fr_1.3fr] lg:gap-12"><div className="space-y-4"><div className="surface rounded-[20px] p-6"><div className="flex size-11 items-center justify-center rounded-xl bg-[#c5ff4116] text-accent"><Mail className="size-5"/></div><h2 className="mt-6 text-lg font-bold">Prefer email?</h2><p className="mt-2 text-sm leading-6 text-muted">Write directly to the Enrivea team. This is also the fallback if the form is unavailable.</p><a href="mailto:contact@enrivea.com" className="mt-5 inline-flex items-center gap-2 break-all text-sm font-bold text-accent hover:underline">contact@enrivea.com <ArrowUpRight className="size-4 shrink-0"/></a></div><div className="surface rounded-[20px] p-6"><div className="flex size-11 items-center justify-center rounded-xl bg-[#c5ff4116] text-accent"><Headset className="size-5"/></div><h2 className="mt-6 text-lg font-bold">Account questions</h2><p className="mt-2 text-sm leading-6 text-muted">Use the email associated with your account and describe the issue. We will never ask for your password or withdrawal access.</p></div><div className="flex items-start gap-3 rounded-[18px] border border-[#4b6440] bg-[#c5ff410b] p-5 text-sm leading-6 text-[#cadcc3]"><ShieldCheck className="mt-0.5 size-5 shrink-0 text-accent"/> Enrivea Signal is a research product. The team cannot provide personalized trade recommendations through support.</div></div><ContactForm/></div></main>;
}
