"use client";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Ban, Eye, ShieldCheck, LogOut, X, UserRound, Search } from "lucide-react";
export type DirectoryUser = {
  id: string; name: string; email: string; role: "user" | "staff" | "admin"; status: "active" | "suspended" | "banned";
  country: string; credits: number; plan: string; access: string; periodEnd: string | null; createdAt: string; verified: boolean; isDemo: boolean; protected: boolean;
  audit: { action: string; after: string; reason: string; date: string; status: string }[];
};
type Change = { action: "set_name" | "set_status" | "set_role" | "set_country" | "revoke_sessions"; value?: string; label: string };
const field = "w-full rounded-xl border border-line bg-[#0b160f] px-3 py-2.5 text-sm";
const button = "inline-flex items-center justify-center gap-2 rounded-xl border border-line px-4 py-2.5 text-xs font-bold transition hover:border-accent/50 disabled:opacity-40";
export function AdminUserDirectory({ users, demo = false }: { users: DirectoryUser[]; demo?: boolean }) {
  const router = useRouter();
  const dialog = useRef<HTMLDialogElement>(null);
  const [selected, setSelected] = useState<string | null>(null);
  const [reason, setReason] = useState(demo ? "Interactive demo account change" : "");
  const [role, setRole] = useState("user");
  const [displayName, setDisplayName] = useState("");
  const [country, setCountry] = useState("");
  const [change, setChange] = useState<Change | null>(null);
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);
  const user = users.find(item => item.id === selected);
  useEffect(() => { if (selected) dialog.current?.showModal(); else dialog.current?.close(); }, [selected]);
  function open(item: DirectoryUser) {
    setDisplayName(item.name); setSelected(item.id); setReason(demo ? "Interactive demo account change" : ""); setRole(item.role); setCountry(item.country); setChange(null); setMessage("");
  }
  async function apply(preview = false) {
    if (!user || (!preview && !change)) return;
    setBusy(true); setMessage("");
    try {
      const response = await fetch("/api/admin/users/" + user.id + (preview ? "/preview" : "/access"), { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(preview ? { reason } : { action: change!.action, value: change!.value, reason }) });
      const data = await response.json();
      if (!response.ok) throw new Error(data.error);
      if (preview) { dialog.current?.close(); router.push(data.url); return; }
      setMessage(change?.action === "set_name" ? "Profile saved and audited." : "Saved and audited. Existing sessions are invalidated on their next request.");
      setChange(null); setReason(demo ? "Interactive demo account change" : ""); router.refresh();
    } catch (error) { setMessage(error instanceof Error ? error.message : "Action unavailable."); }
    finally { setBusy(false); }
  }
  const ready = !busy && reason.trim().length >= 12;
  return <><div className="space-y-3 p-4 md:hidden">{users.map(item => <article key={item.id} className="rounded-2xl border border-line p-4"><div className="flex items-center justify-between gap-3"><h3 className="font-bold">{item.name}</h3><span className={item.status === "active" ? "text-xs text-accent" : "text-xs text-amber-200"}>{item.status}</span></div><p className="mt-2 break-all text-xs text-muted">{item.email}</p><p className="mt-3 text-xs capitalize text-muted">{item.role} · {item.plan} · {item.credits} credits</p><button className={button + " mt-4 w-full"} onClick={() => open(item)} aria-label={"Manage " + item.name}><UserRound className="size-4"/>Manage account</button></article>)}</div><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[850px] text-left text-sm"><thead className="border-b border-line text-[10px] uppercase tracking-widest text-muted"><tr><th className="p-4">Customer</th><th>Access</th><th>Role</th><th>Membership</th><th>Credits</th><th className="pr-4 text-right">Manage</th></tr></thead><tbody className="divide-y divide-line">{users.map(item => <tr key={item.id} className="transition hover:bg-white/[.025]"><td className="p-4"><div className="flex items-center gap-3"><span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-accent/10 font-bold text-accent">{item.name.split(" ").slice(0, 2).map(name => name[0]).join("")}</span><div><p className="font-bold">{item.name} {item.isDemo && <span className="ml-1 text-[9px] uppercase tracking-wide text-muted">Demo</span>}</p><p className="mt-1 text-xs text-muted">{item.email}</p></div></div></td><td><span className={"rounded-full border px-2.5 py-1 text-[10px] font-bold uppercase " + (item.status === "active" ? "border-accent/25 bg-accent/5 text-accent" : item.status === "banned" ? "border-red-400/30 bg-red-400/10 text-red-300" : "border-amber-300/30 bg-amber-300/5 text-amber-200")}>{item.status}</span></td><td className="capitalize text-muted">{item.role}</td><td><span className="capitalize">{item.plan}</span><span className="mt-1 block text-xs capitalize text-muted">{item.access}</span></td><td className="font-mono text-accent">{item.credits.toLocaleString()}</td><td className="pr-4 text-right"><button onClick={() => open(item)} className={button} aria-label={"Manage " + item.name}><UserRound className="size-3.5"/>Manage</button></td></tr>)}</tbody></table>{!users.length && <div className="py-16 text-center"><Search className="mx-auto size-8 text-muted"/><p className="mt-3 text-muted">No accounts match these filters.</p></div>}</div>
  <dialog aria-label="Manage account" ref={dialog} onClose={() => { setSelected(null); setChange(null); }} className="fixed inset-0 m-auto max-h-[90dvh] w-[calc(100%-24px)] max-w-2xl overflow-y-auto rounded-3xl border border-[#38523b] bg-[#101b14] p-0 text-white shadow-2xl backdrop:bg-black/75">{user && <div className="p-5 sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] uppercase tracking-[.2em] text-accent">Account management</p><h2 className="mt-2 text-2xl font-bold">{user.name}</h2><p className="mt-1 break-all text-sm text-muted">{user.email}</p></div><button className={button} aria-label="Close account details" onClick={() => dialog.current?.close()}><X className="size-4"/></button></div>
  <div className="my-5 grid grid-cols-3 gap-3">{[["Status", user.status], ["Plan", user.plan], ["Credits", String(user.credits)]].map(([label, value]) => <div key={label} className="rounded-xl border border-line p-3"><p className="text-[10px] uppercase text-muted">{label}</p><p className="mt-2 font-bold capitalize">{value}</p></div>)}</div>
  <div className="mb-5 flex flex-wrap gap-x-5 gap-y-2 text-xs text-muted"><span>{user.verified ? "Email verified" : "Email unverified"}</span><span>Joined {new Date(user.createdAt).toLocaleDateString()}</span><span>Country: {user.country || "Not set"}</span>{user.periodEnd && <span>Membership ends {new Date(user.periodEnd).toLocaleDateString()}</span>}</div>
  {user.protected && <p className="mb-4 rounded-xl border border-amber-300/25 bg-amber-300/5 p-3 text-xs text-amber-100">Protected administrator or showcase login. Demonstrate access changes on one of the sample customers instead.</p>}
  <label className="block text-xs font-bold text-muted">Audit reason<textarea rows={2} value={reason} maxLength={300} onChange={event => setReason(event.target.value)} className={field + " mt-2"} placeholder="Why is this action needed? At least 12 characters."/></label><p className="mt-2 text-[11px] text-muted">Reasons are recorded for administrators, not sent to the customer.</p>
  <div className="mt-5 grid gap-2 sm:grid-cols-2"><button disabled={!ready || user.protected} onClick={() => setChange({ action: "set_status", value: user.status === "banned" ? "active" : "banned", label: user.status === "banned" ? "Unban and restore access" : "Ban this account" })} className={button + " border-red-400/25 text-red-200"}><Ban className="size-4"/>{user.status === "banned" ? "Unban user" : "Ban user"}</button><button disabled={!ready || user.protected} onClick={() => setChange({ action: "set_status", value: user.status === "active" ? "suspended" : "active", label: user.status === "active" ? "Suspend account access" : "Restore account access" })} className={button}><ShieldCheck className="size-4"/>{user.status === "active" ? "Suspend access" : "Restore access"}</button><button disabled={!ready || user.protected} onClick={() => setChange({ action: "revoke_sessions", label: "Revoke all existing sessions" })} className={button}><LogOut className="size-4"/>Revoke sessions</button><button disabled={!ready || user.role === "admin"} onClick={() => void apply(true)} className={button + " border-accent/40 text-accent"}><Eye className="size-4"/>View as user · read-only</button></div>
  <p className="mt-3 text-xs leading-5 text-muted">Ban and suspension both block login and invalidate existing sessions. Bans remain until explicitly reversed. View as user opens a 15-minute read-only preview without sharing the customer’s credentials.</p>
  {!user.protected && <div className="mt-5 grid gap-4 border-t border-line pt-5 sm:grid-cols-2"><div><label className="text-xs text-muted">Platform role<select aria-label="Platform role" value={role} onChange={e => setRole(e.target.value)} className={field + " mt-2"}><option value="user">User</option><option value="staff">Staff</option></select></label><button className={button + " mt-2 w-full"} disabled={!ready || role === user.role} onClick={() => setChange({ action: "set_role", value: role, label: "Change role to " + role })}>Update role</button></div><div><label className="text-xs text-muted">Verified billing country<input aria-label="Verified billing country" value={country} maxLength={2} onChange={e => setCountry(e.target.value.toUpperCase().replace(/[^A-Z]/g, ""))} className={field + " mt-2"}/></label><button className={button + " mt-2 w-full"} disabled={!ready || country.length !== 2 || country === user.country} onClick={() => setChange({ action: "set_country", value: country, label: "Set independently verified country to " + country })}>Update country</button></div></div>}
  {user.role !== "admin" && <div className="mt-5 border-t border-line pt-5"><label className="text-xs text-muted">Display name<input aria-label="Customer display name" value={displayName} maxLength={100} onChange={e => setDisplayName(e.target.value)} className={field + " mt-2"}/></label><button className={button + " mt-2"} disabled={!ready || displayName.trim().length < 2 || displayName.trim() === user.name} onClick={() => setChange({ action: "set_name", value: displayName.trim(), label: "Save customer display name" })}>Save display name</button></div>}
  {change && <div className="mt-5 rounded-xl border border-amber-300/35 bg-amber-300/5 p-4"><h3 className="font-bold">{change.label}?</h3><p className="mt-2 text-xs text-muted">Account: {user.email}. {change.action === "set_name" ? "This profile edit will be audited." : "This action will be audited and revoke existing sessions."}</p><div className="mt-3 flex gap-2"><button disabled={!ready} onClick={() => void apply()} className={button + " bg-accent text-black"}>{busy ? "Applying…" : "Confirm change"}</button><button disabled={busy} className={button} onClick={() => setChange(null)}>Cancel</button></div></div>}
  {message && <p role="status" className="mt-4 rounded-xl border border-line p-3 text-sm">{message}</p>}
  <section className="mt-6 border-t border-line pt-5"><h3 className="text-sm font-bold">Recent administrative history</h3>{user.audit.length ? user.audit.map((event, index) => <div key={index} className="mt-3 rounded-xl border border-line p-3"><p className="text-xs font-bold capitalize">{event.action.replaceAll("_", " ")} · {event.status}</p><p className="mt-1 text-xs text-muted">{event.reason}</p><p className="mt-2 text-[10px] text-muted">{new Date(event.date).toLocaleString()} · {event.after}</p></div>) : <p className="mt-3 text-xs text-muted">No recorded access changes yet.</p>}</section>
  </div>}</dialog></>;
}
