"use client";

import { useCallback, useEffect, useState } from "react";
import { Users, Copy, RefreshCw, ArrowUpRight, Wallet, Network } from "lucide-react";

type Settings = { enabled: boolean; rates: number[]; cookieDays: number; holdDays: number };
type Row = { id: string; beneficiary: string; buyer: string; level: number; rateBps: number; amountMinor: number; saleMinor: number; currency: string; status: string; createdAt: string; availableAt: string; payoutReference: string; reason: string };
type Report = { config: Settings; code: string; page: number; total: number; referralCount: number; canUpdate?: boolean; canPayout?: boolean; balances: { _id: { currency: string; status: string }; amountMinor: number; count: number }[]; rows: Row[]; referrals: { id: string; name: string; createdAt: string; converted: boolean }[] };
const money = (minor: number, currency: string) => new Intl.NumberFormat("en", { style: "currency", currency }).format(minor / 100);
const inputClass = "mt-2 w-full rounded-xl border border-line bg-[#0b140e] px-3 py-3 text-sm text-white";
const buttonClass = "rounded-xl border border-line px-4 py-2.5 text-sm font-bold disabled:opacity-40 hover:bg-white/5";

export function AffiliateDashboard({ admin = false }: { admin?: boolean }) {
  const [data, setData] = useState<Report | null>(null);
  const [draft, setDraft] = useState<Settings | null>(null);
  const [page, setPage] = useState(1);
  const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState<{ error: boolean; text: string } | null>(null);
  const [reason, setReason] = useState("");
  const [reference, setReference] = useState("");
  const [selected, setSelected] = useState<{ row: Row; action: "pay" | "reverse" } | null>(null);
  const [origin, setOrigin] = useState("");
  const endpoint = admin ? "/api/admin/affiliates" : "/api/affiliates";
  const load = useCallback(async () => {
    const response = await fetch(`${endpoint}?page=${page}`, { cache: "no-store" });
    const payload = await response.json();
    if (!response.ok) throw new Error(payload.error || "Unable to load affiliate data.");
    setData(payload); setDraft(payload.config); setOrigin(window.location.origin);
  }, [endpoint, page]);
  useEffect(() => {
    const controller = new AbortController();
    fetch(`${endpoint}?page=${page}`, { cache: "no-store", signal: controller.signal })
      .then(async response => { const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Unable to load affiliates."); return payload; })
      .then(payload => { setData(payload); setDraft(payload.config); setOrigin(window.location.origin); })
      .catch(error => { if (!controller.signal.aborted) setNotice({ error: true, text: error.message }); });
    return () => controller.abort();
  }, [endpoint, page]);
  async function refresh() { setBusy(true); try { await load(); setNotice({ error: false, text: "Affiliate data refreshed." }); } catch (error) { setNotice({ error: true, text: error instanceof Error ? error.message : "Refresh failed." }); } finally { setBusy(false); } }
  async function mutate(body: unknown) {
    setBusy(true); setNotice(null);
    try {
      const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
      const payload = await response.json();
      if (!response.ok) throw new Error(payload.error || "Changes could not be saved.");
      await load(); setSelected(null); setReason(""); setReference(""); setNotice({ error: false, text: "Changes saved and recorded in the audit trail." });
    } catch (error) { setNotice({ error: true, text: error instanceof Error ? error.message : "Save failed." }); }
    finally { setBusy(false); }
  }
  const link = data ? `${origin}/r/${data.code}` : "";
  const currencies = [...new Set(data?.balances.map(balance => balance._id.currency) ?? [])];
  return <div className="space-y-6">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">{admin ? "Partner operations" : "Grow with Enrivea"}</p><h1 className="mt-3 text-3xl font-black sm:text-4xl">{admin ? "Affiliate control room" : "Your affiliate workspace"}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted">{admin ? "Track first-purchase commissions, configure referral levels, and reconcile payouts." : "Invite people to Enrivea and earn when their first payment is verified. Follow every referral and commission here."}</p></div><button className={buttonClass} disabled={busy} onClick={() => void refresh()}><RefreshCw className="mr-2 inline size-4"/>Refresh</button></div>
    {notice && <div role={notice.error ? "alert" : "status"} className={`rounded-xl border p-4 text-sm ${notice.error ? "border-red-400/40 text-red-200" : "border-accent/30 text-accent"}`}>{notice.text}</div>}
    {!data && !notice && <div className="surface animate-pulse rounded-2xl p-10 text-muted">Loading affiliate activity…</div>}
    {data && <>
      <section className="surface relative overflow-hidden rounded-3xl border border-accent/25 p-6 sm:p-8"><Network className="absolute -right-6 -top-6 size-48 text-accent/5"/><div className="relative"><span className={`rounded-full border px-3 py-1 text-xs font-bold ${data.config.enabled ? "border-accent/30 text-accent" : "border-amber-400/30 text-amber-200"}`}>{data.config.enabled ? "Referrals active" : "New commissions paused"}</span><h2 className="mt-5 text-2xl font-black">{data.config.rates.length === 1 ? "Direct referrals. Clear rewards." : `${data.config.rates.length} levels. One first purchase.`}</h2><p className="mt-2 text-sm text-muted">{data.config.rates.map((rate, index) => `Level ${index + 1}: ${(rate / 100).toFixed(2)}%`).join(" · ")} · {data.config.holdDays}-day hold · {data.config.cookieDays}-day referral window</p>{!admin && <div className="mt-5 flex flex-col gap-3 sm:flex-row"><input aria-label="Your referral link" readOnly value={link} className={inputClass + " mt-0 min-w-0 flex-1"}/><button className="button-primary rounded-xl px-5 py-3 text-sm font-black" onClick={async () => { try { await navigator.clipboard.writeText(link); setNotice({ error: false, text: "Referral link copied." }); } catch { setNotice({ error: true, text: "Copy unavailable. Select and copy the link above." }); } }}><Copy className="mr-2 inline size-4"/>Copy link</button></div>}<p className="mt-4 text-xs leading-5 text-muted">Commissions apply only to the first verified purchase. Refills do not earn again. Earnings are tracked in the payment currency, separately from platform credits. Referral identity is fixed at signup.</p></div></section>
      <div className="grid gap-4 sm:grid-cols-3"><Metric icon={<Users className="size-5"/>} label={admin ? "Referred accounts" : "Direct referrals"} value={String(data.referralCount)}/><Metric icon={<ArrowUpRight className="size-5"/>} label="Commission entries" value={String(data.total)}/><Metric icon={<Wallet className="size-5"/>} label="Payout method" value="Manual settlement"/></div>
      <section className="surface rounded-2xl p-6"><h2 className="text-lg font-black">Earnings overview</h2><p className="mt-1 text-xs text-muted">Totals include all history. Currencies are never combined.</p>{currencies.length ? currencies.map(currency => <div key={currency} className="mt-5 grid gap-3 sm:grid-cols-4">{["pending", "available", "paid", "reversed"].map(status => <div key={status} className="rounded-xl border border-line p-4"><p className="text-xs capitalize text-muted">{status} · {currency}</p><p className="mt-2 text-xl font-black tabular-nums">{money(data.balances.find(balance => balance._id.currency === currency && balance._id.status === status)?.amountMinor ?? 0, currency)}</p></div>)}</div>) : <p className="mt-6 text-sm text-muted">No commissions yet. Earnings appear after a referred account completes its first eligible payment.</p>}</section>
      {admin && draft && data.canUpdate && <form className="surface rounded-2xl p-6" onSubmit={event => { event.preventDefault(); void mutate({ action: "settings", ...draft, reason }); }}><h2 className="text-lg font-black">Program settings</h2><p className="mt-2 text-xs text-muted">Percentages are saved to two decimal places. Updates affect future purchases only; total commission cannot exceed 100%.</p><label className="mt-5 flex items-center gap-3 text-sm"><input type="checkbox" checked={draft.enabled} onChange={event => setDraft({ ...draft, enabled: event.target.checked })}/>Enable new referrals and commissions</label><div className="mt-5 grid gap-4 sm:grid-cols-3"><label className="text-xs text-muted">Commission model<select className={inputClass} value={draft.rates.length} onChange={event => setDraft({ ...draft, rates: Array.from({ length: Number(event.target.value) }, (_, index) => draft.rates[index] ?? 0) })}>{[1, 2, 3, 4, 5].map(count => <option key={count} value={count}>{count === 1 ? "Direct only" : `${count} unilevel levels`}</option>)}</select></label><label className="text-xs text-muted">Referral cookie · days<input className={inputClass} type="number" required min={1} max={90} value={draft.cookieDays} onChange={event => setDraft({ ...draft, cookieDays: Number(event.target.value) })}/></label><label className="text-xs text-muted">Commission hold · days<input className={inputClass} type="number" required min={0} max={90} value={draft.holdDays} onChange={event => setDraft({ ...draft, holdDays: Number(event.target.value) })}/></label></div><div className="mt-4 grid gap-4 sm:grid-cols-3">{draft.rates.map((rate, index) => <label key={index} className="text-xs text-muted">Level {index + 1} commission · %<input type="number" className={inputClass} min={0} max={100} step={0.01} required value={rate / 100} onChange={event => setDraft({ ...draft, rates: draft.rates.map((item, itemIndex) => itemIndex === index ? Math.round(Number(event.target.value) * 100) : item) })}/></label>)}</div><label className="mt-4 block text-xs text-muted">Reason for change<input className={inputClass} required minLength={8} maxLength={300} value={reason} onChange={event => setReason(event.target.value)}/></label><button disabled={busy} className="button-primary mt-5 rounded-xl px-5 py-3 text-sm font-black">{busy ? "Saving…" : "Save affiliate settings"}</button></form>}
      <section className="surface overflow-hidden rounded-2xl"><div className="p-6"><h2 className="text-lg font-black">Commission history</h2><p className="mt-1 text-xs text-muted">Newest first · Pending earnings become available after the hold period.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-y border-line bg-black/20 text-xs text-muted"><tr>{["Date / referral", ...(admin ? ["Affiliate"] : []), "Level / rate", "Purchase", "Commission", "Status", ...(admin && data.canPayout ? ["Actions"] : [])].map(title => <th key={title} className="p-4 font-semibold">{title}</th>)}</tr></thead><tbody>{data.rows.map(row => <tr key={row.id} className="border-b border-line"><td className="p-4"><p>{row.buyer}</p><p className="mt-1 text-xs text-muted">{new Date(row.createdAt).toLocaleDateString()}</p></td>{admin && <td className="p-4">{row.beneficiary}</td>}<td className="p-4">L{row.level} · {(row.rateBps / 100).toFixed(2)}%</td><td className="p-4 tabular-nums">{money(row.saleMinor, row.currency)}</td><td className="p-4 font-bold tabular-nums text-accent">{money(row.amountMinor, row.currency)}</td><td className="p-4"><span className="rounded-full border border-line px-2.5 py-1 text-xs capitalize">{row.status}</span>{row.status === "pending" && <p className="mt-2 text-xs text-muted">Available {new Date(row.availableAt).toLocaleDateString()}</p>}{row.payoutReference && <p className="mt-2 max-w-40 break-all text-xs text-muted">{row.payoutReference}</p>}</td>{admin && data.canPayout && <td className="p-4"><div className="flex gap-2">{row.status === "available" && <button className={buttonClass} disabled={busy} onClick={() => { setSelected({ row, action: "pay" }); setReason(""); setReference(""); }}>Record payout</button>}{["available", "pending"].includes(row.status) && <button className={buttonClass} disabled={busy} onClick={() => { setSelected({ row, action: "reverse" }); setReason(""); }}>Reverse</button>}</div></td>}</tr>)}</tbody></table></div>{!data.rows.length && <p className="p-8 text-center text-sm text-muted">No commission entries on this page.</p>}</section>
      {selected && <form className="surface rounded-2xl border border-accent/30 p-6" onSubmit={event => { event.preventDefault(); void mutate({ action: selected.action, id: selected.row.id, reference, reason }); }}><h2 className="font-black">{selected.action === "pay" ? "Record a completed external payout" : "Reverse unpaid commission"} · {money(selected.row.amountMinor, selected.row.currency)}</h2><p className="mt-2 text-xs text-muted">{selected.action === "pay" ? "This records a payment you have already made. It does not transfer money." : "Use for a refunded or ineligible purchase. This removes the unpaid earning and preserves its history."}</p>{selected.action === "pay" && <label className="mt-4 block text-xs">Payout reference<input className={inputClass} required minLength={4} maxLength={150} value={reference} onChange={event => setReference(event.target.value)}/></label>}<label className="mt-4 block text-xs">Audit reason<input className={inputClass} required minLength={8} maxLength={300} value={reason} onChange={event => setReason(event.target.value)}/></label><div className="mt-4 flex gap-3"><button disabled={busy} className="button-primary rounded-xl px-4 py-3 font-bold">Confirm {selected.action === "pay" ? "payout record" : "reversal"}</button><button type="button" disabled={busy} className={buttonClass} onClick={() => setSelected(null)}>Cancel</button></div></form>}
      <section className="surface rounded-2xl p-6"><h2 className="text-lg font-black">{admin ? "Recent referred accounts" : "Your direct referrals"}</h2><div className="mt-3 divide-y divide-line">{data.referrals.map(referral => <div key={referral.id} className="flex justify-between gap-3 py-4 text-sm"><div>{referral.name}<p className="mt-1 text-xs text-muted">Joined {new Date(referral.createdAt).toLocaleDateString()}</p></div><span className={referral.converted ? "text-accent" : "text-muted"}>{referral.converted ? "First payment verified" : "Awaiting first payment"}</span></div>)}</div>{!data.referrals.length && <p className="mt-4 text-sm text-muted">No referred accounts on this page.</p>}</section>
      <div className="flex items-center justify-between"><button disabled={page <= 1 || busy} className={buttonClass} onClick={() => setPage(page - 1)}>Previous</button><span className="text-xs text-muted">Page {page}</span><button disabled={page * 25 >= Math.max(data.total, data.referralCount) || busy} className={buttonClass} onClick={() => setPage(page + 1)}>Next</button></div>
    </>}
  </div>;
}
function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="surface rounded-2xl p-5"><div className="flex items-center gap-2 text-sm text-muted">{icon}{label}</div><p className="mt-3 text-2xl font-black">{value}</p></div>; }
