import Link from "next/link";
import { AdminBillingAdjustment } from "@/components/admin-billing-adjustment";
import { DemoWorkspace } from "@/models/DemoWorkspace";
import { User } from "@/models/User";

export async function DemoBillingOperations() {
  const records = await DemoWorkspace.find().sort({ updatedAt: -1 }).limit(50).lean();
  for (const record of records) record.creditBalance ??= 0;
  const owners = await User.find({ _id: { $in: records.map(item => item.userId) }, isDemo: true }).select("email role status").lean();
  const emails = new Map(owners.map(user => [String(user._id), user.email]));
  const visible = records.filter(item => emails.has(String(item.userId)));
  const receipts = visible.flatMap(item => item.receipts.filter(receipt => ["activation", "topup"].includes(receipt.kind ?? "")).map(receipt => ({ ...receipt, email: emails.get(String(item.userId)) }))).sort((a, b) => new Date(b.createdAt ?? 0).getTime() - new Date(a.createdAt ?? 0).getTime());
  return <div className="space-y-5"><div className="rounded-xl border border-accent/30 p-4 text-xs text-muted">Demo billing only. Simulated activations and refills are excluded from real revenue. <Link className="text-accent underline" href="/admin/controls">Configure activation and refill packs</Link></div><div className="grid gap-4 sm:grid-cols-3">{[["Demo accounts", visible.length], ["Activated accounts", visible.filter(item => item.activatedAt).length], ["Shared credits", visible.reduce((sum, item) => sum + item.creditBalance, 0)]].map(([label, value]) => <div key={label} className="surface rounded-2xl p-5"><p className="text-xs text-muted">{label}</p><p className="mt-3 text-3xl font-bold text-accent">{value}</p></div>)}</div><section className="surface rounded-2xl p-5"><h2 className="mb-4 font-bold">Activate an account or adjust shared credits</h2><AdminBillingAdjustment demo users={owners.filter(user => user.role !== "admin" && user.status === "active").map(user => ({ id: String(user._id), email: user.email }))}/></section><section className="surface overflow-auto rounded-2xl p-5"><h2 className="mb-4 font-bold">Activation & balances</h2><table className="w-full min-w-[650px] text-left text-sm"><thead className="text-xs text-muted"><tr><th className="pb-3">Customer</th><th>Access</th><th>Activated</th><th>Shared credits</th></tr></thead><tbody>{visible.map(item => <tr key={String(item._id)} className="border-t border-line"><td className="py-4">{emails.get(String(item.userId))}</td><td className={item.activatedAt ? "text-accent" : "text-muted"}>{item.activatedAt ? "Permanent" : "Not activated"}</td><td>{item.activatedAt ? new Date(item.activatedAt).toLocaleString() : "—"}</td><td className="number">{item.creditBalance}</td></tr>)}</tbody></table></section><section className="surface rounded-2xl p-5"><h2 className="mb-4 font-bold">Simulated payments</h2>{receipts.length ? receipts.slice(0, 40).map(item => <div key={item.requestId} className="flex justify-between gap-4 border-t border-line py-4 text-sm"><div>{item.email}<p className="mt-1 text-xs text-muted">{item.kind} · {item.itemId} · {new Date(item.createdAt ?? 0).toLocaleString()}</p></div><span className="text-accent">${item.amount} <small className="block text-muted">Simulated</small></span></div>) : <p className="text-sm text-muted">Make a simulated activation or refill from the demo user Billing page to populate this ledger.</p>}</section></div>;
}
