import { Activity, ArrowUpRight, BarChart3, Check, ChevronRight, CircleDot, LockKeyhole, Radar, ScanSearch, ShieldCheck } from "lucide-react";

const candles = [34, 44, 38, 54, 51, 48, 59, 68, 57, 63, 73, 65, 78, 74, 86, 80, 93, 89, 97];

export function MarketVisual() {
  return <div className="terminal-wrap relative mx-auto w-full max-w-[800px]" aria-label="Illustrative Enrivea Signal research interface">
    <div className="terminal-halo pointer-events-none absolute -inset-8 rounded-[45px]" aria-hidden="true"/>
    <div className="terminal-frame relative overflow-hidden rounded-[25px] border border-[#6a8b35] bg-[#0c140d] shadow-[0_35px_100px_#000e,0_0_48px_#baff3022]">
      <div className="flex items-center justify-between border-b border-[#344934] bg-[#101b12] px-4 py-3.5 sm:px-5"><div className="flex items-center gap-2.5"><span className="flex size-6 items-center justify-center rounded-md bg-accent text-xs font-black text-[#101807]">E</span><span className="text-xs font-black uppercase tracking-[.13em]">Enrivea <span className="text-accent">Signal</span></span></div><span className="rounded-full border border-[#618144] bg-[#bbff3b13] px-2.5 py-1 text-[10px] font-bold uppercase tracking-widest text-accent">Research preview</span></div>
      <div className="grid grid-cols-[84px_minmax(0,1fr)] sm:grid-cols-[108px_minmax(0,1fr)]">
        <aside className="border-r border-[#2a3a2b] bg-[#0e180f] px-2 py-4 sm:px-3"><div className="space-y-1.5"><SidebarItem icon={<BarChart3/>} label="Overview" active/><SidebarItem icon={<Radar/>} label="Scans"/><SidebarItem icon={<ScanSearch/>} label="Ideas"/><SidebarItem icon={<Activity/>} label="Outcomes"/></div><div className="mt-12 hidden border-t border-[#2b3b2a] pt-4 text-[10px] leading-5 text-[#839781] sm:block">Decision support<br/><strong className="text-[#d5e4ca]">Not auto-trading</strong></div></aside>
        <div className="grid min-w-0 gap-2.5 p-2.5 sm:grid-cols-[1.45fr_.85fr] sm:gap-3 sm:p-4">
          <div className="grid min-w-0 gap-2.5 sm:gap-3"><div className="terminal-panel relative flex min-h-[254px] flex-col overflow-hidden rounded-xl p-4 sm:min-h-[320px] sm:p-5"><div className="flex items-start justify-between gap-2"><div><p className="terminal-label">Market structure</p><h3 className="mt-2 text-xl font-bold tracking-[-.04em] sm:text-2xl">BTC<span className="text-[#789074]">/</span>USDT</h3></div><span className="rounded-md border border-[#435b35] px-2 py-1 text-[10px] font-bold text-accent">4h candles</span></div><div className="terminal-chart relative mt-auto h-[150px] sm:h-[205px]"><div className="absolute inset-0 grid-glow opacity-35"/><svg className="absolute inset-0 h-full w-full overflow-visible" viewBox="0 0 460 180" preserveAspectRatio="none" role="img" aria-label="Illustrative rising market line, not live price data"><defs><linearGradient id="heroChartFill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#c5ff41" stopOpacity=".23"/><stop offset="1" stopColor="#c5ff41" stopOpacity="0"/></linearGradient></defs><path d="M0 145 L25 139 L45 150 L66 117 L84 122 L104 107 L121 113 L141 91 L163 101 L183 81 L203 87 L225 71 L245 78 L268 61 L287 69 L310 49 L331 56 L353 37 L376 44 L395 25 L416 36 L439 14 L460 20 L460 180 L0 180Z" fill="url(#heroChartFill)"/><path className="chart-draw" d="M0 145 L25 139 L45 150 L66 117 L84 122 L104 107 L121 113 L141 91 L163 101 L183 81 L203 87 L225 71 L245 78 L268 61 L287 69 L310 49 L331 56 L353 37 L376 44 L395 25 L416 36 L439 14 L460 20" stroke="#c5ff41" strokeWidth="2.6" fill="none" vectorEffect="non-scaling-stroke"/><circle cx="439" cy="14" r="4" fill="#d7ff70"/></svg><div className="absolute bottom-0 left-0 right-0 flex h-[32%] items-end gap-1 opacity-45" aria-hidden="true">{candles.map((height, index) => <span key={index} className="flex-1 bg-[#8fca39]" style={{ height: `${height}%` }}/>)}</div></div><div className="mt-3 flex items-center justify-between border-t border-[#283b2a] pt-3 text-[10px] font-semibold text-[#9db49a]"><span>Closed-candle analysis</span><span className="text-accent">Illustrative chart</span></div></div>
            <div className="terminal-panel flex items-center justify-between gap-3 rounded-xl p-3 sm:p-4"><div><p className="terminal-label">Research result</p><p className="mt-1 text-sm font-bold">Evidence before action</p><p className="mt-1 text-xs text-[#9aaf97]">Thesis · invalidation · expiry</p></div><span className="flex size-9 shrink-0 items-center justify-center rounded-full border border-[#5d7d37] bg-[#c5ff4112] text-accent"><ArrowUpRight className="size-4"/></span></div>
          </div>
          <div className="grid min-w-0 grid-cols-2 gap-2.5 sm:grid-cols-1 sm:gap-3"><div className="terminal-panel flex flex-col rounded-xl p-3.5 sm:p-4"><div className="flex items-center justify-between gap-2"><p className="terminal-label">Decision engine</p><CircleDot className="size-3.5 text-accent"/></div><div className="ai-orbit relative mx-auto my-auto flex size-[96px] items-center justify-center rounded-full border border-[#78a640] sm:size-[140px]"><div className="absolute inset-[10px] rounded-full border border-[#5e863c8a]"/><div className="absolute inset-[22px] rounded-full bg-[radial-gradient(circle,#baff3630,#132311_70%)] blur-[1px]"/><span className="relative text-center text-[10px] font-bold leading-4 text-[#d9f1c5] sm:text-xs">SCREEN<br/><span className="text-accent">EXPLAIN</span><br/>REVIEW</span></div><p className="text-center text-[10px] text-[#9eb39b]">AI explains calculated facts</p></div><div className="terminal-panel rounded-xl p-3.5 sm:p-4"><p className="terminal-label">A guarded flow</p><div className="mt-3 space-y-2 text-[11px] font-semibold text-[#c5d7be]"><FlowRow text="Opportunity detected"/><FlowRow text="Risk levels checked"/><FlowRow text="User reviews idea"/><div className="flex items-center gap-2 text-[#8da18b]"><span className="flex size-4 items-center justify-center rounded-full border border-[#52634a]"><LockKeyhole className="size-2.5"/></span>Order execution pending</div></div></div></div>
        </div>
      </div>
      <div className="flex flex-wrap items-center justify-between gap-2 border-t border-[#344934] bg-[#101a11] px-4 py-2.5 text-[10px] font-bold uppercase tracking-[.1em] text-[#95aa8f] sm:px-5"><span className="inline-flex items-center gap-1.5"><ShieldCheck className="size-3 text-accent"/> User-approved direction</span><span>Not a live signal or return</span></div>
    </div><div className="terminal-chip absolute -right-3 top-[14%] hidden items-center gap-1.5 rounded-lg border border-[#5c7d3a] bg-[#152316] px-3 py-2 text-[11px] font-bold text-[#e2f5d2] shadow-[0_12px_30px_#000a] xl:flex"><span className="size-1.5 rounded-full bg-accent"/> Clear rationale <ChevronRight className="size-3 text-accent"/></div>
  </div>;
}

function SidebarItem({ icon, label, active = false }: { icon: React.ReactNode; label: string; active?: boolean }) { return <div className={`flex items-center gap-2 rounded-lg px-2 py-2 text-[10px] font-bold sm:text-[11px] ${active ? "bg-[#a8ef3524] text-accent" : "text-[#819680]"}`}><span className="[&>svg]:size-3.5">{icon}</span><span className="hidden sm:inline">{label}</span></div>; }
function FlowRow({ text }: { text: string }) { return <div className="flex items-center gap-2"><span className="flex size-4 items-center justify-center rounded-full bg-accent text-[#112008]"><Check className="size-2.5 stroke-[3]"/></span>{text}</div>; }
