import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight, Check, CircleHelp, Coins, ShieldCheck, Workflow } from "lucide-react";
import { plans } from "@/lib/plans";

export const metadata: Metadata = { title: "Pricing", description: "Explore Enrivea Signal's proposed credit-based research plans and how analysis credits work." };

export default function PricingPage() {
  return <main><section className="relative overflow-hidden border-b border-line"><div className="pointer-events-none absolute inset-0 hero-mesh opacity-50"/><div className="relative mx-auto max-w-[1500px] px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="max-w-3xl"><p className="eyebrow">Research access</p><h1 className="display mt-5 text-5xl sm:text-7xl">A plan for the way <span className="text-accent">you research.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-muted">Credits are used for completed market scans, not for guaranteed trade results. The prices below are proposed pilot packages; checkout has not opened.</p></div><div className="mt-14 grid gap-4 lg:grid-cols-3">{plans.map(plan => <div key={plan.id} className={`flex flex-col rounded-[24px] border p-7 sm:p-8 ${plan.featured ? "border-[#a2d74e] bg-[#19271a] accent-glow" : "border-line bg-panel"}`}><div className="flex items-center justify-between gap-2"><span className="text-xs font-bold uppercase tracking-[.15em] text-[#a8bba3]">{plan.audience}</span>{plan.featured && <span className="rounded-full bg-accent px-2.5 py-1 text-[10px] font-black uppercase tracking-wide text-[#0c1409]">Most room to grow</span>}</div><h2 className="mt-7 text-3xl font-semibold tracking-tight">{plan.name}</h2><p className="mt-3 min-h-12 text-sm leading-6 text-muted">{plan.description}</p><div className="mt-8 flex items-baseline gap-1"><span className="text-5xl font-semibold tracking-[-.06em] number">${plan.price}</span><span className="text-muted">/ month</span></div><p className="mt-3 text-sm font-bold text-accent">{plan.credits} analysis credits each month</p><Link href="/register" className={`${plan.featured ? "button-primary" : "button-secondary"} mt-8 inline-flex h-12 items-center justify-center gap-2 rounded-xl text-sm font-bold`}>Explore the workspace <ArrowUpRight className="size-4"/></Link><div className="mt-8 border-t border-line pt-7"><p className="mb-5 text-xs font-bold uppercase tracking-[.14em] text-[#90a38e]">Proposed package</p><ul className="space-y-4">{plan.features.map(feature => <li key={feature} className="flex gap-3 text-sm leading-6 text-[#d0d9ce]"><Check className="mt-1 size-4 shrink-0 text-accent"/>{feature}</li>)}</ul></div></div>)}</div><p className="mt-6 text-sm leading-6 text-muted">No payment is collected in this preview. Package features involving exchange orders, advanced analytics, and priority support are planned, not available today.</p></div></section>
    <section className="mx-auto grid max-w-[1500px] gap-12 px-5 py-24 sm:px-8 lg:grid-cols-[.8fr_1.2fr] lg:px-12 lg:py-28"><div><p className="eyebrow">A transparent unit of usage</p><h2 className="display mt-5 text-4xl sm:text-5xl">What a credit <span className="text-accent">actually buys.</span></h2><p className="mt-6 text-lg leading-8 text-muted">One credit starts a validated research run for a supported Spot pair. You receive either a documented setup or an explicit no-setup result.</p></div><div className="grid gap-4 sm:grid-cols-2"><Info icon={<Coins/>} title="One completed scan" text="A completed scan uses one credit, including when the market does not pass the filters."/><Info icon={<Workflow/>} title="A traceable result" text="Market facts, model explanation when qualified, cutoff time, and signal history remain visible."/><Info icon={<ShieldCheck/>} title="Failed runs are different" text="The system is designed to return credits for failed analyses, with integrity checks visible to operations staff."/><Info icon={<CircleHelp/>} title="No promise of profit" text="A credit funds analysis—not an order, a guaranteed setup, or a return."/></div></section>
    <section className="border-y border-line bg-[#111914]"><div className="mx-auto grid max-w-[1500px] gap-10 px-5 py-24 sm:px-8 lg:grid-cols-[.7fr_1.3fr] lg:px-12"><div><p className="eyebrow">Before checkout opens</p><h2 className="display mt-5 text-4xl sm:text-5xl">Clear terms before <span className="text-accent">a payment.</span></h2></div><div className="space-y-4 text-base leading-8 text-muted"><p>Final plan terms will state the billing cycle, credit expiry, rollover policy, cancellation, refunds, taxes, and which capabilities are available in each eligible country. Those terms are not finalized yet.</p><p>Paid access will open only after a payment provider accepts the business model and Enrivea completes legal and security review for the initial launch countries.</p><p>Read the <Link href="/risk-disclosure" className="font-bold text-accent underline">risk disclosure</Link> before using crypto research. Paper outcomes are simulations and actual account performance can differ materially.</p></div></div></section>
    <section className="mx-auto max-w-[1500px] px-5 py-24 text-center sm:px-8 lg:px-12"><p className="eyebrow">Start with the workspace</p><h2 className="display mx-auto mt-5 max-w-3xl text-4xl sm:text-5xl">Explore the research process <span className="text-accent">before you subscribe.</span></h2><p className="mx-auto mt-6 max-w-xl text-lg leading-8 text-muted">Create an account, review the method, and see how completed scans and paper outcomes are recorded.</p><Link href="/register" className="button-primary mt-8 inline-flex h-12 items-center gap-2 rounded-xl px-6 text-sm">Create your account <ArrowUpRight className="size-4"/></Link></section></main>;
}

function Info({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="surface rounded-[20px] p-6"><span className="text-accent [&>svg]:size-5">{icon}</span><h3 className="mt-7 text-lg font-bold">{title}</h3><p className="mt-3 text-sm leading-7 text-muted">{text}</p></div>; }
