import type { Metadata } from "next";
import Link from "next/link";
import { getServerSession } from "next-auth";
import { ArrowUpRight, BadgeCheck, Check, CircleHelp, Coins, RefreshCcw, ShieldCheck, Workflow } from "lucide-react";
import { connectDB } from "@/lib/db";
import { getPlatformConfig } from "@/lib/platform-config";
import { authOptions } from "@/lib/auth";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Pricing", description: "Activate Enrivea Signal once, then refill shared platform credits only when you need them." };

const money = (minor: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(minor / 100);

export default async function PricingPage() {
  await connectDB();
  const session = await getServerSession(authOptions);
  const config = await getPlatformConfig(Boolean(session?.user?.isDemo));
  const packs = config.creditPacks.filter(pack => pack.enabled);
  return <main><section className="relative overflow-hidden border-b border-line"><div className="pointer-events-none absolute inset-0 hero-mesh opacity-50"/><div className="relative mx-auto max-w-[1500px] px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="grid gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><p className="eyebrow">Simple platform access</p><h1 className="display mt-5 text-5xl sm:text-7xl">Activate once.<br/><span className="text-accent">Research on demand.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-muted">No monthly subscription and no recurring platform fee. Activate your account once, receive a starting credit balance, then refill only when you need more analysis.</p><Link href="/register" className="button-primary mt-8 inline-flex h-12 items-center gap-2 rounded-xl px-6 text-sm font-bold">Create your account <ArrowUpRight className="size-4"/></Link></div><div className="surface rounded-[28px] border-accent/40 p-7 accent-glow sm:p-9"><div className="flex items-center justify-between gap-3"><span className="text-xs font-black uppercase tracking-[.16em] text-accent">Lifetime activation</span><BadgeCheck className="size-6 text-accent"/></div><div className="mt-8 flex items-end gap-3"><span className="number text-6xl font-black tracking-[-.07em]">{money(config.activationPriceMinor)}</span><span className="pb-2 text-sm text-muted">one time</span></div><p className="mt-4 text-lg font-bold text-accent">Includes {config.activationCredits} shared platform credits</p><ul className="mt-8 space-y-4">{["Permanent account activation", "One balance across every enabled product", "Credits remain until they are used", "Refill packs available from your dashboard"].map(item => <li key={item} className="flex gap-3 text-sm text-[#d0d9ce]"><Check className="size-5 shrink-0 text-accent"/>{item}</li>)}</ul><p className="mt-8 border-t border-line pt-5 text-xs leading-5 text-muted">The activation price and included credits are controlled by Enrivea operations and shown before checkout. Crypto research is not a promise of profit.</p></div></div></div></section>
    <section className="mx-auto max-w-[1500px] px-5 py-24 sm:px-8 lg:px-12"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="eyebrow">Refill when needed</p><h2 className="display mt-5 text-4xl sm:text-5xl">Credits that fit your <span className="text-accent">workflow.</span></h2></div><p className="max-w-xl text-sm leading-7 text-muted">Refills add to the same shared balance. Buying credits does not renew or extend anything because activated access does not expire.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{packs.map(pack => <article key={pack.id} className="surface rounded-[22px] p-6"><Coins className="size-5 text-accent"/><p className="mt-7 text-xs font-bold uppercase tracking-widest text-muted">{pack.label}</p><h3 className="mt-3 text-3xl font-black number">{pack.credits} credits</h3><p className="mt-2 text-lg text-accent">{money(pack.priceMinor)}</p><p className="mt-5 text-sm leading-6 text-muted">Added instantly after the payment provider verifies the transaction.</p></article>)}</div></section>
    <section className="border-y border-line bg-[#111914]"><div className="mx-auto grid max-w-[1500px] gap-12 px-5 py-24 sm:px-8 lg:grid-cols-[.8fr_1.2fr] lg:px-12"><div><p className="eyebrow">A transparent unit of usage</p><h2 className="display mt-5 text-4xl sm:text-5xl">What a credit <span className="text-accent">actually buys.</span></h2></div><div className="grid gap-4 sm:grid-cols-2"><Info icon={<Workflow/>} title="Product-specific cost" text="Each product clearly shows its credit cost before you run it. Operations can adjust costs as products evolve."/><Info icon={<RefreshCcw/>} title="One shared balance" text="Activation and refill credits work across every enabled Enrivea product instead of separate plan wallets."/><Info icon={<ShieldCheck/>} title="Failed runs are refunded" text="Failed analysis attempts return their reserved credits, with ledger entries available to operations."/><Info icon={<CircleHelp/>} title="No promise of profit" text="Credits fund platform analysis—not an order, a guaranteed setup, or an investment return."/></div></div></section>
    <section className="mx-auto max-w-[1500px] px-5 py-24 text-center sm:px-8 lg:px-12"><p className="eyebrow">Ready when you are</p><h2 className="display mx-auto mt-5 max-w-3xl text-4xl sm:text-5xl">One activation. <span className="text-accent">No recurring access fee.</span></h2><p className="mx-auto mt-6 max-w-xl text-lg leading-8 text-muted">Create your workspace, activate securely, and control your research spend with a clear credit ledger.</p><Link href="/register" className="button-primary mt-8 inline-flex h-12 items-center gap-2 rounded-xl px-6 text-sm">Get started <ArrowUpRight className="size-4"/></Link></section></main>;
}

function Info({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="surface rounded-[20px] p-6"><span className="text-accent [&>svg]:size-5">{icon}</span><h3 className="mt-7 text-lg font-bold">{title}</h3><p className="mt-3 text-sm leading-7 text-muted">{text}</p></div>; }
