import Link from "next/link";
import { Activity, ArrowRight, ArrowUpRight, BarChart3, BrainCircuit, Check, ChevronRight, CircleCheck, Clock3, DatabaseZap, Gauge, Layers3, LockKeyhole, Radar, ScanSearch, ShieldCheck, Workflow } from "lucide-react";
import { MarketVisual } from "@/components/market-visual";
import { plans } from "@/lib/plans";

const faqs = [
  { question: "Does Enrivea Signal hold my crypto?", answer: "No. The product is designed for research and user-approved exchange trading. Your assets remain in your own exchange account. Live exchange connections are not enabled in this preview." },
  { question: "What does an analysis credit cover?", answer: "One completed market scan costs one credit, including a scan that finds no qualifying setup. A failed scan should not consume a credit. Credit purchases are not active yet." },
  { question: "Does AI decide the entry and stop?", answer: "No. Deterministic filters calculate market conditions and reference levels from closed exchange candles. AI explains the evidence and risks; it does not invent prices." },
  { question: "Can I execute a trade today?", answer: "Not yet. User-confirmed Binance Spot execution is a guarded next integration. No signal can submit an order on its own." },
  { question: "Are paper outcomes real returns?", answer: "No. Paper outcomes use later market candles and explicit fee and slippage assumptions. Real account P&L will require confirmed exchange fills and will be reported separately." },
];

export default function Home() {
  return <main className="marketing-home">
    <section className="hero-scene relative isolate overflow-hidden border-b border-[#3b5630]">
      <div className="hero-landscape absolute inset-0 -z-20" aria-hidden="true"/>
      <div className="hero-shade absolute inset-0 -z-10" aria-hidden="true"/>
      <div className="mx-auto grid max-w-[1520px] items-center gap-12 px-5 pb-20 pt-36 sm:px-8 lg:min-h-[690px] lg:grid-cols-[.87fr_1.13fr] lg:gap-6 lg:px-12 lg:pb-24 lg:pt-36">
        <div className="hero-copy relative z-10 max-w-[640px]"><p className="eyebrow hero-eyebrow">Market intelligence, without the noise</p><h1 className="hero-title mt-5 text-[clamp(3.35rem,5.6vw,6.5rem)] font-bold leading-[.98] tracking-[-.065em] text-white">Smarter research.<br/><span className="text-[#e9f7de]">Steadier</span> <span className="text-accent">decisions.</span></h1><p className="mt-7 max-w-[570px] text-lg leading-[1.6] text-[#d7e4d3] sm:text-xl">See what the market is doing, why a setup qualifies, and where the idea fails—before you decide whether to act.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/register" className="button-primary inline-flex min-h-13 items-center gap-3 rounded-xl px-6 text-sm shadow-[0_12px_45px_#baff263a]">Start researching <ArrowRight className="size-4"/></Link><Link href="#method" className="inline-flex min-h-13 items-center gap-3 rounded-xl border border-[#8cae54] bg-[#07100ab8] px-6 text-sm font-bold text-white transition-colors hover:bg-[#1a2918]">Explore the method <ArrowUpRight className="size-4"/></Link></div><div className="mt-9 flex flex-wrap gap-x-6 gap-y-2 border-t border-[#9ebd7455] pt-5 text-xs font-bold uppercase tracking-[.12em] text-[#c9ddbd]"><span className="inline-flex items-center gap-2"><CircleCheck className="size-3.5 text-accent"/> Explainable</span><span className="inline-flex items-center gap-2"><CircleCheck className="size-3.5 text-accent"/> Risk-aware</span><span className="inline-flex items-center gap-2"><CircleCheck className="size-3.5 text-accent"/> User-directed</span></div><p className="mt-5 text-xs text-[#bdcfb2]">Development preview · No live exchange orders or paid plans.</p></div>
        <div className="hero-terminal relative z-10"><MarketVisual/></div>
      </div>
      <div className="hero-bottom-glow pointer-events-none absolute bottom-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-accent to-transparent"/>
    </section>

    <section className="border-b border-line bg-[#0d150e]"><div className="mx-auto grid max-w-[1520px] gap-5 px-5 py-6 sm:px-8 lg:grid-cols-[.95fr_2fr] lg:items-center lg:px-12"><p className="text-xs font-black uppercase tracking-[.18em] text-[#a9c492]">Built around a disciplined decision</p><div className="grid grid-cols-2 gap-4 text-sm font-semibold text-[#d5e3cf] sm:grid-cols-4"><TrustItem icon={<DatabaseZap/>} text="Closed market data"/><TrustItem icon={<BrainCircuit/>} text="Explainable thesis"/><TrustItem icon={<ShieldCheck/>} text="Defined risk"/><TrustItem icon={<BarChart3/>} text="Honest outcomes"/></div></div></section>

    <section id="product" className="mx-auto max-w-[1520px] px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="flex flex-wrap items-end justify-between gap-7"><div><p className="eyebrow">Always a clearer view</p><h2 className="section-heading mt-4 max-w-3xl">Useful intelligence. <span className="text-accent">Visible safeguards.</span></h2></div><p className="max-w-md text-base leading-7 text-muted">A research workspace for investors who want more than an alert. Every idea connects evidence, levels, timing, and an outcome record.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><ValueCard icon={<Radar/>} title="Structured discovery" text="Screen supported Binance Spot pairs for trend, breakout, volume, and volatility on closed candles."/><ValueCard icon={<BrainCircuit/>} title="Clear rationale" text="Read an AI-written thesis based on calculated facts, alongside limitations and a specific risk note."/><ValueCard icon={<Gauge/>} title="Risk before reward" text="Entry reference, invalidation, target, data cutoff, and expiry sit together—not in separate tabs."/><ValueCard icon={<Activity/>} title="Accountable results" text="Forward paper outcomes are kept apart from real exchange P&L, which is not available yet."/></div></section>

    <section id="method" className="method-section border-y border-[#354a32] bg-[#0d160f]"><div className="mx-auto max-w-[1520px] px-5 py-20 sm:px-8 lg:px-12 lg:py-24"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="eyebrow">A clearer path through the market</p><h2 className="section-heading mt-4">Observe. Evaluate. <span className="text-accent">Decide.</span></h2></div><p className="max-w-md text-base leading-7 text-muted">The product separates market observation from AI explanation and from any user action. No signal places a trade by itself.</p></div><div className="mt-12 grid gap-4 lg:grid-cols-3"><ProcessCard number="01" icon={<ScanSearch/>} title="Observe" text="Select a supported Spot pair. The scanner uses fully closed 4-hour candles and records when no setup qualifies." tags={["Trend", "Breakout", "Volume", "Volatility"]}/><ProcessCard number="02" icon={<Layers3/>} title="Evaluate" text="Inspect the calculated levels, plain-language thesis, risk note, model version, and time limit as one decision file." tags={["Market facts", "AI context", "Defined risk", "Expiry"]}/><ProcessCard number="03" icon={<CircleCheck/>} title="Decide" text="Keep control of the next step. User-approved Spot execution is planned, but live order submission is not yet active." tags={["Review", "Approve", "Execute later", "Track"]}/></div></div></section>

    <section className="mx-auto grid max-w-[1520px] items-center gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[1.06fr_.94fr] lg:gap-20 lg:px-12 lg:py-28"><div className="insight-panel relative overflow-hidden rounded-[24px] border border-[#5c7c3d] bg-[#101b12] p-4 shadow-[0_25px_75px_#0007] sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#344932] pb-4"><div><p className="terminal-label">The decision file</p><h3 className="mt-1 text-xl font-bold">One place for the whole case</h3></div><span className="rounded-full border border-[#5e7f3d] bg-[#c5ff4114] px-3 py-1 text-[11px] font-bold text-accent">Interface concept</span></div><div className="mt-4 grid gap-3 sm:grid-cols-[1.15fr_.85fr]"><div className="rounded-xl border border-[#354b32] bg-[#0b150d] p-5"><div className="flex items-center gap-2 text-sm font-bold"><span className="flex size-8 items-center justify-center rounded-lg bg-[#c5ff4117] text-accent"><Radar className="size-4"/></span> Research summary</div><div className="mt-5 space-y-3"><InsightRow label="Market evidence" value="Trend · volume · structure"/><InsightRow label="Why it matters" value="Plain-language explanation"/><InsightRow label="Where it fails" value="Defined invalidation level"/><InsightRow label="Time boundary" value="Data cutoff and expiry"/></div></div><div className="rounded-xl border border-[#354b32] bg-[#0b150d] p-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#a1b89a]">Outcome discipline</p><div className="mt-6 flex items-center gap-3"><span className="flex size-11 items-center justify-center rounded-full border border-[#8ab74d] bg-[#c5ff4112] text-accent"><Workflow className="size-5"/></span><div className="text-sm font-bold">Publication first.<br/>Observation after.</div></div><div className="mt-6 border-t border-[#334934] pt-4 text-xs leading-5 text-muted">Paper results use later candles and disclosed assumptions. They are not fills, investment returns, or a promise of performance.</div></div></div></div><div><p className="eyebrow">Deeper insight. Better judgment.</p><h2 className="section-heading mt-5">See the reason <span className="text-accent">behind every idea.</span></h2><p className="mt-6 max-w-xl text-lg leading-8 text-muted">A research signal should be understandable even when you choose not to trade it. Enrivea Signal keeps the inputs, rationale, risk, and eventual paper result together.</p><ul className="mt-8 space-y-3 text-sm font-semibold text-[#d8e7d1]"><Bullet>Calculated levels from market data, not model guesses</Bullet><Bullet>A specific invalidation point and expiry</Bullet><Bullet>Paper and real performance shown separately</Bullet></ul><Link href="/register" className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-accent hover:underline">Explore the workspace <ArrowRight className="size-4"/></Link></div></section>

    <section id="safeguards" className="security-band relative overflow-hidden border-y border-[#344b2e]"><div className="mx-auto grid max-w-[1520px] gap-9 px-5 py-16 sm:px-8 lg:grid-cols-[1fr_1fr] lg:items-center lg:px-12"><div><p className="eyebrow">Security first, always</p><h2 className="section-heading mt-4 max-w-2xl">Your assets stay <span className="text-accent">at your exchange.</span></h2><p className="mt-5 max-w-xl text-base leading-7 text-[#c9d8c3]">Enrivea Signal is being designed without custody or withdrawal permission. Connected trading will require scoped keys, an order preview, and your explicit approval.</p><p className="mt-4 text-sm text-[#a9bc9f]">Exchange connectivity is still in development and will not be activated before security and legal review.</p></div><div className="grid gap-3 sm:grid-cols-2"><SecurityPoint icon={<LockKeyhole/>} title="No withdrawal scope"/><SecurityPoint icon={<ShieldCheck/>} title="User confirmation"/><SecurityPoint icon={<DatabaseZap/>} title="Traceable research"/><SecurityPoint icon={<Workflow/>} title="Order reconciliation"/></div></div></section>

    <section className="mx-auto max-w-[1520px] px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="eyebrow">Control without complexity</p><h2 className="section-heading mt-4">Powerful tools. <span className="text-accent">Clear limits.</span></h2></div><Link href="/about" className="inline-flex items-center gap-2 text-sm font-bold text-accent hover:underline">Explore the platform <ArrowUpRight className="size-4"/></Link></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><ToolCard icon={<Radar/>} title="Research desk" text="Run a supported Spot scan and review the complete outcome." art="pulse"/><ToolCard icon={<Layers3/>} title="Decision history" text="Return to a thesis with the same inputs and cutoff it was published with." art="layers"/><ToolCard icon={<Clock3/>} title="Forward tracking" text="Paper outcomes are observed after publication, never backfilled as real trades." art="timeline"/><ToolCard icon={<BarChart3/>} title="Performance clarity" text="A transparent paper scorecard today; exchange P&L only after verified fills." art="bars"/></div></section>

    <section className="border-y border-line bg-[#0e160f]"><div className="mx-auto grid max-w-[1520px] gap-10 px-5 py-20 sm:px-8 lg:grid-cols-[.85fr_1.15fr] lg:px-12"><div><p className="eyebrow">Plans for the next stage</p><h2 className="section-heading mt-4">Research that scales <span className="text-accent">with you.</span></h2><p className="mt-5 max-w-lg text-base leading-7 text-muted">Three proposed monthly plans with analysis credits. Paid checkout is inactive while provider approval and billing safeguards are completed.</p><Link href="/pricing" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-accent hover:underline">Compare all plan details <ArrowRight className="size-4"/></Link></div><div className="grid gap-3 sm:grid-cols-3">{plans.map(plan => <div key={plan.id} className={`rounded-2xl border p-5 ${plan.featured ? "border-[#8cb347] bg-[#20301b]" : "border-[#354532] bg-[#151e16]"}`}><p className="text-xs font-black uppercase tracking-[.14em] text-[#a6bd97]">{plan.audience}</p><h3 className="mt-4 text-xl font-bold">{plan.name}</h3><p className="mt-2 text-sm text-muted">{plan.credits} analyses / month</p><p className="mt-6 border-t border-[#4c6440] pt-4 text-xs font-semibold text-[#d6e8c6]">Proposed pilot plan</p></div>)}</div></div></section>

    <section id="faq" className="mx-auto grid max-w-[1520px] gap-10 px-5 py-20 sm:px-8 lg:grid-cols-[.68fr_1.32fr] lg:gap-20 lg:px-12 lg:py-28"><div><p className="eyebrow">Straight answers</p><h2 className="section-heading mt-4">Clarity extends <span className="text-accent">beyond the chart.</span></h2><p className="mt-5 text-base leading-7 text-muted">The difference between what is available, what is planned, and what is not promised should always be clear.</p></div><div className="divide-y divide-[#354833] border-y border-[#354833]">{faqs.map(item => <details key={item.question} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 text-base font-bold marker:hidden">{item.question}<ChevronRight className="size-5 shrink-0 text-accent transition-transform group-open:rotate-90"/></summary><p className="max-w-2xl pb-2 pt-4 text-sm leading-7 text-muted">{item.answer}</p></details>)}</div></section>

    <section className="mx-auto max-w-[1520px] px-5 pb-16 sm:px-8 lg:px-12"><div className="closing-scene relative overflow-hidden rounded-[24px] border border-[#83ad3f] px-6 py-12 sm:px-10 lg:flex lg:items-center lg:justify-between lg:gap-10"><div className="relative z-10"><p className="eyebrow">An Enrivea product</p><h2 className="mt-4 max-w-2xl text-3xl font-bold tracking-[-.04em] sm:text-4xl">Move from market noise to an informed decision.</h2><p className="mt-3 max-w-xl text-base text-[#d1dfc8]">Begin with research you can inspect. Stay in control of what comes next.</p></div><Link href="/register" className="button-primary relative z-10 mt-7 inline-flex min-h-12 shrink-0 items-center gap-3 rounded-xl px-6 text-sm lg:mt-0">Create your workspace <ArrowRight className="size-4"/></Link></div><p className="mt-5 text-center text-xs text-[#899e83]">Crypto assets are volatile. Research is not personalized investment advice. No return is guaranteed.</p></section>
  </main>;
}

function TrustItem({ icon, text }: { icon: React.ReactNode; text: string }) { return <div className="flex items-center gap-2.5"><span className="text-accent [&>svg]:size-4">{icon}</span>{text}</div>; }
function ValueCard({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <article className="value-card group rounded-2xl border border-[#344633] bg-[#121b14] p-6"><div className="flex size-12 items-center justify-center rounded-xl border border-[#506c37] bg-[#c5ff4112] text-accent [&>svg]:size-5">{icon}</div><h3 className="mt-8 text-lg font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-muted">{text}</p><div className="mt-8 h-px w-12 bg-accent transition-all duration-300 group-hover:w-full"/></article>; }
function ProcessCard({ number, icon, title, text, tags }: { number: string; icon: React.ReactNode; title: string; text: string; tags: string[] }) { return <article className="process-card rounded-[22px] border border-[#3b5434] bg-[#121e13] p-6 sm:p-7"><div className="flex items-start justify-between"><span className="rounded-lg border border-[#668b3e] px-2.5 py-1 text-sm font-black text-accent">{number}</span><span className="flex size-11 items-center justify-center rounded-full bg-[#c5ff4117] text-accent [&>svg]:size-5">{icon}</span></div><h3 className="mt-7 text-2xl font-bold tracking-[-.04em]">{title}</h3><p className="mt-3 min-h-20 text-sm leading-7 text-muted">{text}</p><div className="mt-6 grid grid-cols-2 gap-2 border-t border-[#3c5336] pt-5">{tags.map(tag => <span key={tag} className="inline-flex items-center gap-2 rounded-lg border border-[#344d2f] bg-[#1b2a19] px-2.5 py-2 text-xs font-semibold text-[#cadcc1]"><Check className="size-3 shrink-0 text-accent"/>{tag}</span>)}</div></article>; }
function InsightRow({ label, value }: { label: string; value: string }) { return <div className="flex flex-wrap items-center justify-between gap-2 border-b border-[#243625] pb-2 text-xs"><span className="text-[#96aa91]">{label}</span><strong className="text-[#e1efda]">{value}</strong></div>; }
function Bullet({ children }: { children: React.ReactNode }) { return <li className="flex items-center gap-3"><Check className="size-4 shrink-0 rounded-full border border-accent p-0.5 text-accent"/>{children}</li>; }
function SecurityPoint({ icon, title }: { icon: React.ReactNode; title: string }) { return <div className="flex items-center gap-3 rounded-xl border border-[#627d43] bg-[#0b150bb8] px-4 py-4 text-sm font-bold"><span className="text-accent [&>svg]:size-5">{icon}</span>{title}</div>; }
function ToolCard({ icon, title, text, art }: { icon: React.ReactNode; title: string; text: string; art: string }) { return <article className="tool-card relative flex min-h-[285px] flex-col overflow-hidden rounded-2xl border border-[#344a31] bg-[#121b13] p-6"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-full bg-[#c5ff4115] text-accent [&>svg]:size-5">{icon}</span><h3 className="text-base font-bold">{title}</h3></div><p className="mt-4 text-sm leading-6 text-muted">{text}</p><div className={`tool-art tool-art-${art} mt-auto h-20`} aria-hidden="true"><span/><span/><span/><span/><span/></div></article>; }
