import Link from "next/link";
import { Activity, ArrowRight, ArrowUpRight, BarChart3, BrainCircuit, Check, ChevronRight, CircleCheck, Gauge, Layers3, ShieldCheck, Zap } from "lucide-react";
import { MarketVisual } from "@/components/market-visual";

const coins = [
  { glyph: "₿", name: "Bitcoin", pair: "BTC / USDT", tone: "btc" },
  { glyph: "Ξ", name: "Ethereum", pair: "ETH / USDT", tone: "eth" },
  { glyph: "◎", name: "Solana", pair: "SOL / USDT", tone: "sol" },
];
const faqs = [
  { question: "Does Enrivea Signal hold my crypto?", answer: "No. The product is designed for research and user-approved exchange trading. Your assets remain in your own exchange account. Live exchange connections are not enabled in this preview." },
  { question: "What does an analysis credit cover?", answer: "One completed market scan costs one credit, including a scan that finds no qualifying setup. A failed scan should not consume a credit. Credit purchases are not active yet." },
  { question: "Does AI decide the entry and stop?", answer: "No. Deterministic filters calculate market conditions and reference levels from closed exchange candles. AI explains the evidence and risks; it does not invent prices." },
  { question: "Can I execute a trade today?", answer: "Not yet. User-confirmed Binance Spot execution is a guarded next integration. No signal can submit an order on its own." },
  { question: "Are paper outcomes real returns?", answer: "No. Paper outcomes use later market candles and explicit fee and slippage assumptions. Real account P&L will require confirmed exchange fills and will be reported separately." },
];

export default function Home() {
  return <main className="marketing-home">
    <section className="hero-scene relative isolate overflow-hidden border-b border-[#3b5630]"><div className="hero-landscape absolute inset-0 -z-20" aria-hidden="true"/><div className="hero-shade absolute inset-0 -z-10" aria-hidden="true"/><div className="mx-auto grid max-w-[1520px] items-center gap-12 px-5 pb-20 pt-36 sm:px-8 lg:min-h-[690px] lg:grid-cols-[.87fr_1.13fr] lg:gap-6 lg:px-12 lg:pb-24 lg:pt-36"><div className="hero-copy relative z-10 max-w-[640px]"><p className="eyebrow hero-eyebrow">Market intelligence, without the noise</p><h1 className="hero-title mt-5 text-[clamp(3.35rem,5.6vw,6.5rem)] font-bold leading-[.98] tracking-[-.065em] text-white">Smarter research.<br/><span className="text-[#e9f7de]">Steadier</span> <span className="text-accent">decisions.</span></h1><p className="mt-7 max-w-[570px] text-lg leading-[1.6] text-[#d7e4d3] sm:text-xl">See what the market is doing, why a setup qualifies, and where the idea fails—before you decide whether to act.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/register" className="button-primary inline-flex min-h-13 items-center gap-3 rounded-xl px-6 text-sm shadow-[0_12px_45px_#baff263a]">Start researching <ArrowRight className="size-4"/></Link><Link href="#method" className="inline-flex min-h-13 items-center gap-3 rounded-xl border border-[#8cae54] bg-[#07100ab8] px-6 text-sm font-bold text-white transition-colors hover:bg-[#1a2918]">Explore the method <ArrowUpRight className="size-4"/></Link></div><div className="mt-9 flex flex-wrap gap-x-6 gap-y-2 border-t border-[#9ebd7455] pt-5 text-xs font-bold uppercase tracking-[.12em] text-[#c9ddbd]"><span className="inline-flex items-center gap-2"><CircleCheck className="size-3.5 text-accent"/> Explainable</span><span className="inline-flex items-center gap-2"><CircleCheck className="size-3.5 text-accent"/> Risk-aware</span><span className="inline-flex items-center gap-2"><CircleCheck className="size-3.5 text-accent"/> User-directed</span></div><p className="mt-5 text-xs text-[#bdcfb2]">Development preview · No live exchange orders or paid plans.</p></div><div className="hero-terminal relative z-10"><MarketVisual/></div></div><div className="hero-bottom-glow pointer-events-none absolute bottom-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-accent to-transparent"/></section>

    <section className="coin-universe border-b border-[#344531]" aria-label="Supported research pairs"><div className="mx-auto max-w-[1520px] px-5 pt-6 sm:px-8 lg:px-12"><div className="flex flex-wrap items-baseline justify-between gap-2"><p className="eyebrow text-[#a6c785]">Research universe / Binance Spot</p><p className="text-xs text-[#8ea286]">Supported pairs · not live prices</p></div></div><div className="coin-marquee mt-4 overflow-hidden pb-5"><div className="coin-track flex w-max items-center gap-3">{[0, 1, 2, 3].map(copy => <div key={copy} className="flex shrink-0 items-center gap-3" aria-hidden={copy > 0}>{coins.map(coin => <div key={`${copy}-${coin.name}`} className="coin-token flex items-center gap-3 rounded-full border border-[#425838] bg-[#111b12] px-4 py-2.5"><span className={`coin-glyph coin-${coin.tone}`}>{coin.glyph}</span><span className="text-sm font-bold text-[#e3eddc]">{coin.name}</span><span className="ml-2 border-l border-[#40513c] pl-3 text-xs font-bold tracking-widest text-accent">{coin.pair}</span></div>)}</div>)}</div></div></section>

    <section id="product" className="mx-auto max-w-[1520px] px-5 pt-12 sm:px-8 lg:px-12"><p className="eyebrow text-[#aac38b]">Four things every idea should make clear</p><div className="feature-rail mt-5 grid border-y border-[#3b5035] md:grid-cols-2 lg:grid-cols-4"><RailFeature icon={<Zap/>} title="Fresh evidence" text="Closed-candle market structure, not recycled calls."/><RailFeature icon={<Gauge/>} title="Defined risk" text="Entry reference, invalidation, target, and expiry."/><RailFeature icon={<BrainCircuit/>} title="Readable reasoning" text="AI context grounded in calculated market facts."/><RailFeature icon={<BarChart3/>} title="Honest results" text="Forward paper outcomes, never passed off as fills."/></div></section>

    <section id="method" className="method-section border-b border-[#354a32]"><div className="mx-auto max-w-[1520px] px-5 pb-16 pt-16 sm:px-8 lg:px-12 lg:pb-20 lg:pt-20"><p className="eyebrow">A clearer path through the market</p><h2 className="section-heading mt-3">Observe. Evaluate. <span className="text-accent">Decide.</span></h2><div className="process-grid mt-10 grid gap-8 lg:grid-cols-3 lg:gap-0"><ProcessStage number="01" title="Observe" text="Screen BTC, ETH, and SOL Spot markets with fully closed candles. When no setup qualifies, the record says so." art="observe"/><ProcessStage number="02" title="Evaluate" text="Read one decision file with calculated levels, the AI thesis, a risk note, data cutoff, and expiry." art="evaluate"/><ProcessStage number="03" title="Decide" text="Keep control of what comes next. User-approved exchange execution is planned—not active in this preview." art="decide"/></div><div className="process-art-wide hidden lg:block" role="img" aria-label="Illustration of a market globe flowing into analysis layers and a user decision"/><div className="mt-5 flex flex-wrap gap-x-7 gap-y-2 border-t border-[#344832] pt-5 text-xs font-semibold uppercase tracking-widest text-[#a8bd9d]"><span>01 / Market data</span><span>02 / AI explanation</span><span>03 / Your decision</span></div></div></section>

    <section className="mx-auto grid max-w-[1520px] items-center gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[1.08fr_.92fr] lg:gap-16 lg:px-12 lg:py-28"><PerformancePreview/><div><p className="eyebrow">Deeper insight. Brighter decisions.</p><h2 className="section-heading mt-5">See the reason <span className="text-accent">behind every idea.</span></h2><p className="mt-6 max-w-xl text-lg leading-8 text-muted">An alert is only the start. Enrivea Signal keeps the evidence, boundaries, and observed paper outcome attached to the same idea so you can inspect the whole case.</p><ul className="mt-8 space-y-4 text-sm font-semibold text-[#d8e7d1]"><Bullet>Source market facts and a clear data cutoff</Bullet><Bullet>Calculated levels, AI thesis, and risk note</Bullet><Bullet>Paper tracking separated from future real P&amp;L</Bullet><Bullet>No automatic exchange order from a signal</Bullet></ul><Link href="/register" className="mt-8 inline-flex items-center gap-2 border-b border-accent pb-1 text-sm font-bold text-accent">Explore the workspace <ArrowRight className="size-4"/></Link></div></section>

    <section className="tools-section mx-auto max-w-[1520px] px-5 pb-20 sm:px-8 lg:px-12 lg:pb-28"><div className="flex flex-wrap items-end justify-between gap-4 border-t border-[#354832] pt-9"><div><p className="eyebrow">Powerful tools. A simpler way.</p><h2 className="section-heading mt-3">Control without complexity.</h2></div><Link href="/about" className="inline-flex items-center gap-2 text-sm font-bold text-accent">Explore the platform <ArrowUpRight className="size-4"/></Link></div><div className="mt-8 grid gap-3 md:grid-cols-2 lg:grid-cols-4"><ToolCard icon={<ShieldCheck/>} title="Risk controls" text="See where an idea fails before you consider acting." art="pulse"/><ToolCard icon={<Layers3/>} title="Decision history" text="Keep the same facts and cutoff with every published thesis." art="layers"/><ToolCard icon={<Activity/>} title="Market context" text="Separate an observed setup from noise and uncertainty." art="timeline"/><ToolCard icon={<BarChart3/>} title="Performance clarity" text="Track forward paper results without calling them live P&L." art="bars"/></div></section>

    <section id="safeguards" className="security-showcase relative overflow-hidden border-y border-[#4c6a36]"><div className="security-visual absolute inset-0" aria-hidden="true"/><div className="security-wash absolute inset-0" aria-hidden="true"/><div className="relative mx-auto grid max-w-[1520px] gap-8 px-5 py-16 sm:px-8 lg:min-h-[400px] lg:grid-cols-[1fr_.5fr] lg:items-center lg:px-12"><div className="max-w-[640px]"><p className="eyebrow">Security first. Always.</p><h2 className="section-heading mt-4">Built for <span className="text-accent">disciplined access.</span></h2><p className="mt-5 max-w-xl text-base leading-7 text-[#d0dfc8]">Your assets remain at your exchange. The planned Spot connection will use scoped credentials and require a fresh preview and explicit approval before any order.</p><div className="mt-8 flex flex-wrap gap-x-5 gap-y-3 text-xs font-bold text-[#d9eccb]"><SecurityItem>No withdrawal scope</SecurityItem><SecurityItem>Scoped exchange keys</SecurityItem><SecurityItem>Order confirmation</SecurityItem></div><p className="mt-6 text-xs text-[#a7b99d]">Exchange connectivity is not active; security and legal review are required before launch.</p></div><div className="hidden justify-self-end text-right text-xs font-bold uppercase leading-7 tracking-[.2em] text-[#bbd4aa] lg:block">Your security<br/>Our foundation<br/>A more confident<br/>Tomorrow</div></div></section>

    <section className="mx-auto max-w-[1520px] px-5 py-16 sm:px-8 lg:px-12 lg:py-20"><p className="eyebrow">Built honestly, released deliberately</p><div className="mt-4 flex flex-wrap items-end justify-between gap-4"><h2 className="section-heading">What&apos;s here. <span className="text-accent">What comes next.</span></h2><Link href="/pricing" className="inline-flex items-center gap-2 text-sm font-bold text-accent">Proposed plans <ArrowRight className="size-4"/></Link></div><div className="readiness-grid mt-9 grid border-y border-[#3a4d35] md:grid-cols-3"><Readiness state="Available in preview" title="Spot research" text="Structured scans, decision files, and forward paper tracking."/><Readiness state="In development" title="User-approved execution" text="Binance Spot connection, order preview, and confirmation."/><Readiness state="Awaiting approval" title="Paid memberships" text="Three proposed monthly plans; checkout remains off."/></div></section>

    <section id="faq" className="border-t border-[#344732] bg-[#0c150e]"><div className="mx-auto grid max-w-[1520px] gap-10 px-5 py-20 sm:px-8 lg:grid-cols-[.68fr_1.32fr] lg:gap-20 lg:px-12"><div><p className="eyebrow">Straight answers</p><h2 className="section-heading mt-4">Details that <span className="text-accent">matter.</span></h2><p className="mt-5 text-base leading-7 text-muted">Know what the product does, what it is building toward, and what it does not promise.</p></div><div className="divide-y divide-[#354833] border-y border-[#354833]">{faqs.map(item => <details key={item.question} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 text-base font-bold marker:hidden">{item.question}<ChevronRight className="size-5 shrink-0 text-accent transition-transform group-open:rotate-90"/></summary><p className="max-w-2xl pb-2 pt-4 text-sm leading-7 text-muted">{item.answer}</p></details>)}</div></div></section>

    <section className="mx-auto max-w-[1520px] px-5 py-7 sm:px-8 lg:px-12"><div className="closing-scene relative overflow-hidden rounded-[24px] border border-[#83ad3f] px-6 py-12 sm:px-10 lg:flex lg:items-center lg:justify-between lg:gap-10"><div className="relative z-10"><p className="eyebrow">An Enrivea product</p><h2 className="mt-4 max-w-2xl text-3xl font-bold tracking-[-.04em] sm:text-4xl">Move from market noise to an informed decision.</h2><p className="mt-3 max-w-xl text-base text-[#d1dfc8]">Begin with research you can inspect. Stay in control of what comes next.</p></div><Link href="/register" className="button-primary relative z-10 mt-7 inline-flex min-h-12 shrink-0 items-center gap-3 rounded-xl px-6 text-sm lg:mt-0">Create your workspace <ArrowRight className="size-4"/></Link></div><p className="mt-5 text-center text-xs text-[#899e83]">Crypto assets are volatile. Research is not personalized investment advice. No return is guaranteed.</p></section>
  </main>;
}

function RailFeature({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="rail-feature flex items-start gap-4 px-3 py-7 lg:px-6"><span className="flex size-11 shrink-0 items-center justify-center rounded-full bg-[#c5ff4116] text-accent [&>svg]:size-5">{icon}</span><div><h3 className="text-base font-bold">{title}</h3><p className="mt-1 text-sm leading-6 text-muted">{text}</p></div></div>; }
function ProcessStage({ number, title, text, art }: { number: string; title: string; text: string; art: string }) { return <article className="process-stage lg:px-8 first:lg:pl-0 last:lg:pr-0"><div className="flex items-start gap-4"><span className="rounded-md border border-[#688c3c] px-2 py-1 font-mono text-sm font-bold text-accent">{number}</span><div><h3 className="text-2xl font-bold tracking-[-.04em]">{title}</h3><p className="mt-2 max-w-sm text-sm leading-7 text-muted">{text}</p></div></div><div className={`process-art-mobile process-art-${art} mt-3 h-52 lg:hidden`} role="img" aria-label={`${title} illustration`}/></article>; }
function PerformancePreview() { return <div className="performance-preview relative overflow-hidden rounded-[22px] border border-[#668d3d] bg-[#101b12] p-3 shadow-[0_25px_80px_#0009] sm:p-5"><div className="rounded-[15px] border border-[#354b30] bg-[#0d160e] p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-[#33482e] pb-4"><div><p className="terminal-label">Performance workspace</p><h3 className="mt-1 text-lg font-bold">Evidence over exaggeration</h3></div><span className="rounded-full border border-[#547538] px-2.5 py-1 text-[10px] font-bold text-accent">Interface preview</span></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4"><PreviewStat label="Research ideas" value="Recorded"/><PreviewStat label="Paper results" value="Forward only"/><PreviewStat label="Live orders" value="Disabled"/><PreviewStat label="Realized P&L" value="Not yet"/></div><div className="mt-5 grid gap-4 lg:grid-cols-[1.35fr_.65fr]"><div className="rounded-xl border border-[#31472f] bg-[#0a140c] p-4"><div className="flex items-center justify-between gap-3"><p className="text-xs font-bold text-[#d8e9cf]">Forward observation timeline</p><span className="text-[10px] text-[#9fb695]">Illustrative · no returns shown</span></div><div className="preview-chart relative mt-4 h-[180px] overflow-hidden"><div className="absolute inset-0 grid-glow opacity-60"/><svg className="relative h-full w-full" viewBox="0 0 520 180" preserveAspectRatio="none" role="img" aria-label="Schematic research observation timeline; not performance data"><defs><linearGradient id="previewArea" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#c5ff41" stopOpacity=".20"/><stop offset="1" stopColor="#c5ff41" stopOpacity="0"/></linearGradient></defs><path d="M0 145 L48 140 L90 128 L132 120 L173 125 L215 104 L260 110 L304 92 L348 97 L391 74 L435 82 L478 58 L520 61 L520 180 L0 180Z" fill="url(#previewArea)"/><path d="M0 145 L48 140 L90 128 L132 120 L173 125 L215 104 L260 110 L304 92 L348 97 L391 74 L435 82 L478 58 L520 61" fill="none" stroke="#c5ff41" strokeWidth="2.5" vectorEffect="non-scaling-stroke"/><path d="M132 0V180M391 0V180" stroke="#779350" strokeDasharray="4 5" opacity=".65"/></svg></div><div className="flex justify-between border-t border-[#2d422a] pt-3 text-[10px] font-bold uppercase tracking-wider text-[#91a78a]"><span>Scan</span><span>Publish</span><span>Observe</span><span>Close / expire</span></div></div><div className="rounded-xl border border-[#31472f] bg-[#0a140c] p-4"><p className="text-xs font-bold text-[#d8e9cf]">What is measured</p><div className="mt-5 space-y-4 text-xs"><PreviewMeasure label="Market facts" width="88%"/><PreviewMeasure label="Risk definition" width="72%"/><PreviewMeasure label="Paper observation" width="58%"/></div><p className="mt-6 border-t border-[#2d422a] pt-4 text-xs leading-5 text-[#9caf98]">Visual guide only. Your account starts with no fabricated trades or returns.</p></div></div></div></div>; }
function PreviewStat({ label, value }: { label: string; value: string }) { return <div className="border-r border-[#34482f] pr-2 last:border-r-0"><p className="text-[10px] font-bold uppercase tracking-wider text-[#8da587]">{label}</p><p className="mt-2 text-sm font-bold text-[#e4f3d9]">{value}</p></div>; }
function PreviewMeasure({ label, width }: { label: string; width: string }) { return <div><div className="flex justify-between"><span className="text-[#a8bda0]">{label}</span><Check className="size-3 text-accent"/></div><div className="mt-2 h-1.5 rounded-full bg-[#263a24]"><div className="h-full rounded-full bg-gradient-to-r from-[#6d9c32] to-accent" style={{ width }}/></div></div>; }
function Bullet({ children }: { children: React.ReactNode }) { return <li className="flex items-center gap-3"><Check className="size-4 shrink-0 rounded-full border border-accent p-0.5 text-accent"/>{children}</li>; }
function ToolCard({ icon, title, text, art }: { icon: React.ReactNode; title: string; text: string; art: string }) { return <article className="tool-card relative flex min-h-[270px] flex-col overflow-hidden rounded-2xl border border-[#344a31] bg-[#121b13] p-6"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-full bg-[#c5ff4115] text-accent [&>svg]:size-5">{icon}</span><h3 className="text-base font-bold">{title}</h3></div><p className="mt-4 text-sm leading-6 text-muted">{text}</p><div className={`tool-art tool-art-${art} mt-auto h-20`} aria-hidden="true"><span/><span/><span/><span/><span/></div></article>; }
function SecurityItem({ children }: { children: React.ReactNode }) { return <span className="inline-flex items-center gap-2"><CircleCheck className="size-3.5 text-accent"/>{children}</span>; }
function Readiness({ state, title, text }: { state: string; title: string; text: string }) { return <div className="readiness-item py-6 md:px-7 first:md:pl-0 last:md:pr-0"><p className="text-[11px] font-black uppercase tracking-[.16em] text-accent">{state}</p><h3 className="mt-3 text-lg font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted">{text}</p></div>; }
