import mongoose, { Schema, type InferSchemaType, type Model } from "mongoose";

const opportunitySchema = new Schema({
  opportunityId: { type: String, required: true },
  symbol: { type: String, required: true },
  interval: { type: String, required: true },
  side: { type: String, enum: ["BUY", "SELL"], required: true },
  entry: { type: Number, required: true },
  stop: { type: Number, required: true },
  target: { type: Number, required: true },
  confidence: { type: Number, min: 0, max: 100, required: true },
  rationale: { type: String, required: true },
  strategySlug: { type: String, default: "ai-router" },
  strategyName: { type: String, default: "AI Strategy Router" },
  strategyVersion: { type: Number, min: 1, default: 1 },
  amountUsdt: { type: Number, min: 10, max: 100000, default: 250 },
  estimatedQuantity: { type: Number, min: 0, default: null },
  potentialProfitUsdt: { type: Number, min: 0, default: null },
  potentialLossUsdt: { type: Number, min: 0, default: null },
  riskReward: { type: Number, min: 0, default: null },
  markPrice: { type: Number, min: 0, default: null },
  exitPrice: { type: Number, min: 0, default: null },
  positionPnlUsdt: { type: Number, default: null },
  pnlPct: { type: Number, default: null },
  realizedPnlUsdt: { type: Number, default: null },
  status: { type: String, enum: ["pending", "accepted", "rejected", "expired", "invalidated", "closed_target", "closed_stop", "closed_manual", "auto_queued", "simulated_fill", "blocked"], default: "pending" },
  invalidationDirection: { type: String, enum: ["below", "above"], required: true },
  invalidationPrice: { type: Number, min: 0, required: true },
  invalidationInstruction: { type: String, required: true },
  invalidationReason: { type: String, default: null },
  expiresAt: { type: Date, required: true },
  createdAt: { type: Date, default: Date.now },
  decidedAt: { type: Date, default: null },
  openedAt: { type: Date, default: null },
  closedAt: { type: Date, default: null },
}, { _id: false });

const autopilotTradeSchema = new Schema({
  tradeId: { type: String, required: true },
  symbol: { type: String, required: true },
  side: { type: String, enum: ["BUY", "SELL"], required: true },
  status: { type: String, enum: ["open", "closed_target", "closed_stop", "closed_manual", "cancelled", "blocked"], required: true },
  entryPrice: { type: Number, min: 0, required: true },
  markPrice: { type: Number, min: 0, default: null },
  exitPrice: { type: Number, min: 0, default: null },
  stopPrice: { type: Number, min: 0, required: true },
  targetPrice: { type: Number, min: 0, required: true },
  amountUsdt: { type: Number, min: 0, required: true },
  quantity: { type: Number, min: 0, required: true },
  pnlUsdt: { type: Number, default: 0 },
  pnlPct: { type: Number, default: 0 },
  openedAt: { type: Date, required: true },
  closedAt: { type: Date, default: null },
  exchange: { type: String, default: "Binance Spot · Demo" },
  strategySlug: { type: String, default: "trend-breakout" },
  strategyName: { type: String, default: "Trend + Breakout" },
  strategyVersion: { type: Number, min: 1, default: 1 },
}, { _id: false });

const schema = new Schema({
  userId: { type: Schema.Types.ObjectId, ref: "User", required: true, unique: true },
  isDemo: { type: Boolean, default: false },
  autopilotStatus: { type: String, enum: ["paused", "running", "emergency_stopped"], default: "paused" },
  maxPositionUsd: { type: Number, min: 10, max: 100000, default: 250 },
  maxDailyTrades: { type: Number, min: 1, max: 50, default: 3 },
  dailyLossLimitPct: { type: Number, min: 0.25, max: 20, default: 2 },
  allowedSymbols: { type: [String], default: ["BTCUSDT", "ETHUSDT", "SOLUSDT"] },
  approvalStrategySlug: { type: String, default: "ai-router" },
  autopilotStrategySlug: { type: String, default: "trend-breakout" },
  opportunities: { type: [opportunitySchema], default: [] },
  autopilotTrades: { type: [autopilotTradeSchema], default: [] },
  revision: { type: Number, default: 0 },
}, { timestamps: true });

export type TradingCompanionProfileRecord = InferSchemaType<typeof schema>;
export const TradingCompanionProfile = (mongoose.models.TradingCompanionProfile as Model<TradingCompanionProfileRecord> | undefined) ?? mongoose.model<TradingCompanionProfileRecord>("TradingCompanionProfile", schema);
